"""add_user_activity_tracking_columns

Revision ID: 2879f513c1dd
Revises: 019061ee4d9d
Create Date: 2026-08-20 09:36:16.357995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2879f513c1dd'
down_revision: Union[str, Sequence[str], None] = '019061ee4d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_logout_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_failed_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_login_at')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_logout_at')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
