"""initial_schema

Revision ID: ee800d0eaf23
Revises: 
Create Date: 2026-08-07 16:45:42.866455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee800d0eaf23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('mh_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='farmer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_index(op.f('ix_farmers_mh_number'), 'farmers', ['mh_number'], unique=True)
    op.create_index(op.f('ix_farmers_mobile'), 'farmers', ['mobile'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'field_worker', 'lab_worker', 'office_worker', 'stock_manager', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bank_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('ifsc_code', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('passbook_photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id')
    )
    op.create_index(op.f('ix_bank_details_id'), 'bank_details', ['id'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_gst_number', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=True),
    sa.Column('ggn_number', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.create_table('item_master_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.Enum('Box', 'Liner Bag', 'Puneet', 'Pouch', 'Grape Guard', 'Angle Board', 'Pallet', 'Strapping Roll', 'Clip', 'Sticker', name='material_type'), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('unit_of_measure', sa.Enum('pieces', 'kg', 'rolls', name='unit_of_measure'), nullable=False),
    sa.Column('scale_level', sa.Enum('per_box', 'per_container', name='scale_level'), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_master_materials_id'), 'item_master_materials', ['id'], unique=False)
    op.create_table('item_master_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('pack_size', sa.Enum('4 Kg', '4.5 Kg', '5 Kg', name='pack_size'), nullable=False),
    sa.Column('compliance_type', sa.Enum('EU', 'Non-Testing', name='compliance_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_master_products_id'), 'item_master_products', ['id'], unique=False)
    op.create_table('pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pallet_type', sa.Enum('Big', 'Mini', name='pallet_type'), nullable=False),
    sa.Column('total_boxes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('created', 'pre_cooling', 'dispatched', name='pallet_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pallet_id')
    )
    op.create_index(op.f('ix_pallets_id'), 'pallets', ['id'], unique=False)
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('plot_number', sa.String(), nullable=False),
    sa.Column('plot_mh_code', sa.String(), nullable=True),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('area_acres', sa.Numeric(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('taluka', sa.String(), nullable=True),
    sa.Column('survey_no', sa.String(), nullable=True),
    sa.Column('gps_lat', sa.Numeric(), nullable=True),
    sa.Column('gps_long', sa.Numeric(), nullable=True),
    sa.Column('pruning_date', sa.Date(), nullable=True),
    sa.Column('approx_harvest_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id', 'plot_number', name='uq_plots_farmer_plot_number')
    )
    op.create_index(op.f('ix_plots_id'), 'plots', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('supplier_ref', sa.String(), nullable=True),
    sa.Column('other_refs', sa.String(), nullable=True),
    sa.Column('dispatch_through', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('supplier_address', sa.Text(), nullable=True),
    sa.Column('supplier_email', sa.String(), nullable=True),
    sa.Column('supplier_gst', sa.String(), nullable=True),
    sa.Column('assessable_value', sa.Numeric(), nullable=True),
    sa.Column('cgst_total', sa.Numeric(), nullable=True),
    sa.Column('sgst_total', sa.Numeric(), nullable=True),
    sa.Column('freight', sa.String(), nullable=True),
    sa.Column('other_charges', sa.Numeric(), nullable=False),
    sa.Column('grand_total', sa.Numeric(), nullable=True),
    sa.Column('total_in_words', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', 'completed', name='po_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('bom_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_container', sa.Integer(), nullable=False),
    sa.Column('qty_per_box', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['item_master_materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['item_master_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_entries_id'), 'bom_entries', ['id'], unique=False)
    op.create_table('pre_cooling_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('num_pallets', sa.Integer(), nullable=True),
    sa.Column('num_boxes', sa.Integer(), nullable=True),
    sa.Column('in_time', sa.Time(), nullable=True),
    sa.Column('in_berry_temp', sa.Numeric(), nullable=True),
    sa.Column('out_time', sa.Time(), nullable=True),
    sa.Column('out_berry_temp', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_cooling_records_id'), 'pre_cooling_records', ['id'], unique=False)
    op.create_table('purchase_order_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=True),
    sa.Column('particulars', sa.String(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('qty_kg', sa.Numeric(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('kg_per_unit', sa.Numeric(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('gst_percent', sa.Numeric(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_line_items_id'), 'purchase_order_line_items', ['id'], unique=False)
    op.create_table('season_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Registered', 'Field QC Passed', 'Field QC Failed', 'Lab Passed', 'Lab Failed', 'Under Contract', 'Harvested (partial)', 'Weighed', 'Arrival QC Passed', 'Arrival QC Failed', 'Packed', 'Palletised', 'Pre-Cooled', name='registration_status'), nullable=False),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plot_id', 'season_year', name='uq_season_registrations_plot_season')
    )
    op.create_index(op.f('ix_season_registrations_id'), 'season_registrations', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_registration_id', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('rate_per_kg', sa.Numeric(), nullable=False),
    sa.Column('rejection_percent', sa.Numeric(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_registration_id'], ['season_registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_registration_id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('field_qc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_registration_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('planned_sampling_date', sa.Date(), nullable=True),
    sa.Column('tentative_harvest_date', sa.Date(), nullable=True),
    sa.Column('fruit_colour', sa.Enum('Green', 'Milky Green', 'Yellow', name='fruit_colour'), nullable=True),
    sa.Column('tss_percent', sa.Numeric(), nullable=True),
    sa.Column('thrips_percent', sa.Numeric(), nullable=True),
    sa.Column('bhuri_percent', sa.Numeric(), nullable=True),
    sa.Column('black_spot_percent', sa.Numeric(), nullable=True),
    sa.Column('cercospora_percent', sa.Numeric(), nullable=True),
    sa.Column('overall_observation', sa.Enum('Good', 'Very Good', 'Excellent', name='overall_observation'), nullable=True),
    sa.Column('exportable_fruit_percent', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('Pass', 'Fail', name='field_qc_result'), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_registration_id'], ['season_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_qc_id'), 'field_qc', ['id'], unique=False)
    op.create_table('harvests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_registration_id', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('supervisor_name', sa.String(), nullable=True),
    sa.Column('supervisor_contact', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_registration_id'], ['season_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvests_id'), 'harvests', ['id'], unique=False)
    op.create_table('lab_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_registration_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('sampling_date', sa.Date(), nullable=True),
    sa.Column('seal_no', sa.String(), nullable=True),
    sa.Column('variety_confirmed', sa.String(), nullable=True),
    sa.Column('area_ha_2a', sa.Numeric(), nullable=True),
    sa.Column('yield_4b_mt', sa.Numeric(), nullable=True),
    sa.Column('seal_photo_url', sa.String(), nullable=True),
    sa.Column('documents_2a4b_url', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('tss_value', sa.Numeric(), nullable=True),
    sa.Column('result', sa.Enum('Pass', 'Fail', name='lab_result'), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_registration_id'], ['season_registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_registration_id')
    )
    op.create_index(op.f('ix_lab_samples_id'), 'lab_samples', ['id'], unique=False)
    op.create_table('arrival_qc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('fruit_colour_green_pct', sa.Numeric(), nullable=True),
    sa.Column('fruit_colour_milky_pct', sa.Numeric(), nullable=True),
    sa.Column('fruit_colour_yellow_pct', sa.Numeric(), nullable=True),
    sa.Column('tss_percent', sa.Numeric(), nullable=True),
    sa.Column('thrips_percent', sa.Numeric(), nullable=True),
    sa.Column('bhuri_percent', sa.Numeric(), nullable=True),
    sa.Column('black_spot_percent', sa.Numeric(), nullable=True),
    sa.Column('cercospora_percent', sa.Numeric(), nullable=True),
    sa.Column('overall_observation', sa.Enum('Good', 'Very Good', 'Excellent', name='overall_observation'), nullable=True),
    sa.Column('result', sa.Enum('Pass', 'Fail', name='arrival_qc_result'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('harvest_id')
    )
    op.create_index(op.f('ix_arrival_qc_id'), 'arrival_qc', ['id'], unique=False)
    op.create_table('packaging_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('slip_no', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('pack_size', sa.Enum('4 Kg', '4.5 Kg', '5 Kg', name='pack_size'), nullable=False),
    sa.Column('compliance_type', sa.Enum('EU', 'Non-Testing', name='compliance_type'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(), nullable=False),
    sa.Column('rejection_contract_kg', sa.Numeric(), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('actual_rejection_kg', sa.Numeric(), nullable=True),
    sa.Column('actual_rejection_pct', sa.Numeric(), nullable=True),
    sa.Column('num_boxes', sa.Integer(), nullable=False),
    sa.Column('num_pallets', sa.Integer(), nullable=True),
    sa.Column('ggn_number', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_index(op.f('ix_packaging_records_id'), 'packaging_records', ['id'], unique=False)
    op.create_table('vehicle_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_no', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('num_crates', sa.Integer(), nullable=True),
    sa.Column('approx_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_trips_id'), 'vehicle_trips', ['id'], unique=False)
    op.create_table('palletisation_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('packaging_record_id', sa.Integer(), nullable=False),
    sa.Column('num_boxes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packaging_record_id'], ['packaging_records.id'], ),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_palletisation_lots_id'), 'palletisation_lots', ['id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('in', 'auto_out', 'adjustment', name='movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('packaging_record_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['item_master_materials.id'], ),
    sa.ForeignKeyConstraint(['packaging_record_id'], ['packaging_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.create_table('weighing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_trip_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('slip_no', sa.String(), nullable=True),
    sa.Column('supervisor_name', sa.String(), nullable=True),
    sa.Column('num_crates', sa.Integer(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(), nullable=False),
    sa.Column('rejection_pct', sa.Numeric(), nullable=True),
    sa.Column('rejection_kg', sa.Numeric(), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('slip_photo_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_trip_id'], ['vehicle_trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_trip_id')
    )
    op.create_index(op.f('ix_weighing_records_id'), 'weighing_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weighing_records_id'), table_name='weighing_records')
    op.drop_table('weighing_records')
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_palletisation_lots_id'), table_name='palletisation_lots')
    op.drop_table('palletisation_lots')
    op.drop_index(op.f('ix_vehicle_trips_id'), table_name='vehicle_trips')
    op.drop_table('vehicle_trips')
    op.drop_index(op.f('ix_packaging_records_id'), table_name='packaging_records')
    op.drop_table('packaging_records')
    op.drop_index(op.f('ix_arrival_qc_id'), table_name='arrival_qc')
    op.drop_table('arrival_qc')
    op.drop_index(op.f('ix_lab_samples_id'), table_name='lab_samples')
    op.drop_table('lab_samples')
    op.drop_index(op.f('ix_harvests_id'), table_name='harvests')
    op.drop_table('harvests')
    op.drop_index(op.f('ix_field_qc_id'), table_name='field_qc')
    op.drop_table('field_qc')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_season_registrations_id'), table_name='season_registrations')
    op.drop_table('season_registrations')
    op.drop_index(op.f('ix_purchase_order_line_items_id'), table_name='purchase_order_line_items')
    op.drop_table('purchase_order_line_items')
    op.drop_index(op.f('ix_pre_cooling_records_id'), table_name='pre_cooling_records')
    op.drop_table('pre_cooling_records')
    op.drop_index(op.f('ix_bom_entries_id'), table_name='bom_entries')
    op.drop_table('bom_entries')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_plots_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_pallets_id'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_index(op.f('ix_item_master_products_id'), table_name='item_master_products')
    op.drop_table('item_master_products')
    op.drop_index(op.f('ix_item_master_materials_id'), table_name='item_master_materials')
    op.drop_table('item_master_materials')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_bank_details_id'), table_name='bank_details')
    op.drop_table('bank_details')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_farmers_mobile'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_mh_number'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
